version: '3.8'

services:
  django:
    build:
      context: ./bin/django/
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media
    command: gunicorn home.wsgi:application --bind 0.0.0.0:8000
  nginx:
    build: ./bin/nginx
    volumes:
      - static_volume:/opt/static
      - media_volume:/opt/app/media
    ports:
      - 4000:80
    depends_on:
      - django

volumes:
  static_volume:
  media_volume: