x-env-postgres: &env-postgres
  POSTGRES_NAME: ${POSTGRES_NAME}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

x-env-django: &env-django
  SECRET_KEY: ${SECRET_KEY}
  DEBUG: ${DEBUG}
  ALLOWED_HOSTS: ${ALLOWED_HOSTS}

x-env-node: &env-node
  VITE_NODE_ENV: ${VITE_NODE_ENV}
  VITE_FQDN_FRONTEND: ${VITE_FQDN_FRONTEND}
  VITE_FQDN_BACKEND: ${VITE_FQDN_BACKEND}

services:
  db:
    image: postgres
    container_name: hr-postgres
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    environment:
      <<: *env-postgres
  django:
    build: ./bin/django/
    container_name: hr-django
    volumes:
      - ./backend:/opt/app/
    expose:
      - 8000
    environment:
      <<: *env-postgres
      <<: *env-django
    depends_on:
      - db
  node:
    build: ./bin/node
    container_name: hr-node
    volumes:
      - ./frontend:/opt/app
      - ./frontend/node_modules/:/opt/app/node_modules
    command: yarn start --host
    expose:
      - 3000
    environment:
      <<: *env-node

volumes:
  db:
  django:
  frontend: